services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_ACCESS_SECRET: "access_secret"
      JWT_REFRESH_SECRET: "refresh_secret"
      SERVER_PORT: "8080"
      GOOGLE_CLIENT_ID: "54294385906-li0djhcpjeapemcfq72pfiq4i7oliv8d.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URL: "http://localhost:8080/auth/google/callback"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "auth_db"
      SMTP_HOST: "smtp.sendgrid.net"
      SMTP_PORT: "587"
      SMTP_USER: "apikey"
      SMTP_PASSWORD: "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"
      EMAIL_VERIFICATION_SECRET: "email_verification_secret"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
