services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_ACCESS_SECRET: "access_secret"
      JWT_REFRESH_SECRET: "refresh_secret"
      DATABASE_URL: "postgres://user:password@db:5432/auth_db?sslmode=disable"
      SERVER_PORT: "8080"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_NAME: "auth_db"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: